
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 3344
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shine_development

test:
  <<: *default
  database: shine_test


#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: shine_production
  username: shine
  password: <%= ENV['SHINE_DATABASE_PASSWORD'] %>
